name: performance-benchmark

on:
  workflow_dispatch:
  workflow_call:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev]

      - name: Run volatility benchmark
        env:
          PYTHONPATH: src
        run: |
          python scripts/benchmarks/ohlc_volatility_perf.py --rows 100000 --tickers 500 --repeats 1 --interval 1m
